string BEGGAR = "beggar";

void openGate(entity target, entity door, entity callscriptfunction)
{
    string keyName = door.getKey("used_by");
    entity key = sys.getEntity(keyName);
    $player1.replaceInvItem(key, $null_entity);
}

void frobCandlestick(entity ent)
{
	entity candle = ent.getBindMaster();
	candle.remove();

	frob_item(ent);
}

void removeAI()
{
    sys.getEntity(BEGGAR).remove();
}

// main - keep at bottom
void main()
{
    sys.waitFrame();
}